global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask:5000']
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb:3306']
